
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "transformServiceService", targetNamespace = "http://transform/", wsdlLocation = "file:/users/alumnos-12-13/a0307011/pruebaPractica/TransformServiceService.wsdl")
public class TransformServiceService
    extends Service
{

    private final static URL TRANSFORMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSFORMSERVICESERVICE_EXCEPTION;
    private final static QName TRANSFORMSERVICESERVICE_QNAME = new QName("http://transform/", "transformServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/users/alumnos-12-13/a0307011/pruebaPractica/TransformServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSFORMSERVICESERVICE_WSDL_LOCATION = url;
        TRANSFORMSERVICESERVICE_EXCEPTION = e;
    }

    public TransformServiceService() {
        super(__getWsdlLocation(), TRANSFORMSERVICESERVICE_QNAME);
    }

    public TransformServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSFORMSERVICESERVICE_QNAME, features);
    }

    public TransformServiceService(URL wsdlLocation) {
        super(wsdlLocation, TRANSFORMSERVICESERVICE_QNAME);
    }

    public TransformServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSFORMSERVICESERVICE_QNAME, features);
    }

    public TransformServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransformServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransformService
     */
    @WebEndpoint(name = "transformServicePort")
    public TransformService getTransformServicePort() {
        return super.getPort(new QName("http://transform/", "transformServicePort"), TransformService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransformService
     */
    @WebEndpoint(name = "transformServicePort")
    public TransformService getTransformServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://transform/", "transformServicePort"), TransformService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSFORMSERVICESERVICE_EXCEPTION!= null) {
            throw TRANSFORMSERVICESERVICE_EXCEPTION;
        }
        return TRANSFORMSERVICESERVICE_WSDL_LOCATION;
    }

}
