
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "transformService", targetNamespace = "http://transform/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransformService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transformText", targetNamespace = "http://transform/", className = "client.TransformText")
    @ResponseWrapper(localName = "transformTextResponse", targetNamespace = "http://transform/", className = "client.TransformTextResponse")
    @Action(input = "http://transform/transformService/transformTextRequest", output = "http://transform/transformService/transformTextResponse")
    public String transformText(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
